package defs

const PRM_ID = "ID"
const PRM_TIMEOUT = "TIMEOUT"
const PRM_PRIORITY = "PRIORITY"
const PRM_POP_LIMIT = "POPLIMIT"
const PRM_PAYLOAD = "PAYLOAD"
const PRM_DELIVERY_INTERVAL = "DELIVERYINTERVAL"
const PRM_TESTING = "TESTING"
