// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: queue_info/service_desc.proto

/*
	Package queue_info is a generated protocol buffer package.

	It is generated from these files:
		queue_info/service_desc.proto

	It has these top-level messages:
		ServiceDescription
*/
package queue_info

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ServiceDescription struct {
	ExportId  uint64 `protobuf:"varint,1,req,name=export_id,json=exportId" json:"export_id"`
	SType     string `protobuf:"bytes,2,req,name=s_type,json=sType" json:"s_type"`
	Name      string `protobuf:"bytes,3,req,name=name" json:"name"`
	CreateTs  int64  `protobuf:"varint,4,req,name=create_ts,json=createTs" json:"create_ts"`
	Disabled  bool   `protobuf:"varint,5,req,name=disabled" json:"disabled"`
	ToDelete  bool   `protobuf:"varint,6,req,name=to_delete,json=toDelete" json:"to_delete"`
	ServiceId string `protobuf:"bytes,7,req,name=service_id,json=serviceId" json:"service_id"`
}

func (m *ServiceDescription) Reset()                    { *m = ServiceDescription{} }
func (*ServiceDescription) ProtoMessage()               {}
func (*ServiceDescription) Descriptor() ([]byte, []int) { return fileDescriptorServiceDesc, []int{0} }

func (m *ServiceDescription) GetExportId() uint64 {
	if m != nil {
		return m.ExportId
	}
	return 0
}

func (m *ServiceDescription) GetSType() string {
	if m != nil {
		return m.SType
	}
	return ""
}

func (m *ServiceDescription) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceDescription) GetCreateTs() int64 {
	if m != nil {
		return m.CreateTs
	}
	return 0
}

func (m *ServiceDescription) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *ServiceDescription) GetToDelete() bool {
	if m != nil {
		return m.ToDelete
	}
	return false
}

func (m *ServiceDescription) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceDescription)(nil), "queue_info.ServiceDescription")
}
func (this *ServiceDescription) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ServiceDescription)
	if !ok {
		that2, ok := that.(ServiceDescription)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ExportId != that1.ExportId {
		return false
	}
	if this.SType != that1.SType {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.CreateTs != that1.CreateTs {
		return false
	}
	if this.Disabled != that1.Disabled {
		return false
	}
	if this.ToDelete != that1.ToDelete {
		return false
	}
	if this.ServiceId != that1.ServiceId {
		return false
	}
	return true
}
func (this *ServiceDescription) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 11)
	s = append(s, "&queue_info.ServiceDescription{")
	s = append(s, "ExportId: "+fmt.Sprintf("%#v", this.ExportId)+",\n")
	s = append(s, "SType: "+fmt.Sprintf("%#v", this.SType)+",\n")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "CreateTs: "+fmt.Sprintf("%#v", this.CreateTs)+",\n")
	s = append(s, "Disabled: "+fmt.Sprintf("%#v", this.Disabled)+",\n")
	s = append(s, "ToDelete: "+fmt.Sprintf("%#v", this.ToDelete)+",\n")
	s = append(s, "ServiceId: "+fmt.Sprintf("%#v", this.ServiceId)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringServiceDesc(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *ServiceDescription) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ServiceDescription) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintServiceDesc(dAtA, i, uint64(m.ExportId))
	dAtA[i] = 0x12
	i++
	i = encodeVarintServiceDesc(dAtA, i, uint64(len(m.SType)))
	i += copy(dAtA[i:], m.SType)
	dAtA[i] = 0x1a
	i++
	i = encodeVarintServiceDesc(dAtA, i, uint64(len(m.Name)))
	i += copy(dAtA[i:], m.Name)
	dAtA[i] = 0x20
	i++
	i = encodeVarintServiceDesc(dAtA, i, uint64(m.CreateTs))
	dAtA[i] = 0x28
	i++
	if m.Disabled {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	dAtA[i] = 0x30
	i++
	if m.ToDelete {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	dAtA[i] = 0x3a
	i++
	i = encodeVarintServiceDesc(dAtA, i, uint64(len(m.ServiceId)))
	i += copy(dAtA[i:], m.ServiceId)
	return i, nil
}

func encodeVarintServiceDesc(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ServiceDescription) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovServiceDesc(uint64(m.ExportId))
	l = len(m.SType)
	n += 1 + l + sovServiceDesc(uint64(l))
	l = len(m.Name)
	n += 1 + l + sovServiceDesc(uint64(l))
	n += 1 + sovServiceDesc(uint64(m.CreateTs))
	n += 2
	n += 2
	l = len(m.ServiceId)
	n += 1 + l + sovServiceDesc(uint64(l))
	return n
}

func sovServiceDesc(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozServiceDesc(x uint64) (n int) {
	return sovServiceDesc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ServiceDescription) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ServiceDescription{`,
		`ExportId:` + fmt.Sprintf("%v", this.ExportId) + `,`,
		`SType:` + fmt.Sprintf("%v", this.SType) + `,`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`CreateTs:` + fmt.Sprintf("%v", this.CreateTs) + `,`,
		`Disabled:` + fmt.Sprintf("%v", this.Disabled) + `,`,
		`ToDelete:` + fmt.Sprintf("%v", this.ToDelete) + `,`,
		`ServiceId:` + fmt.Sprintf("%v", this.ServiceId) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringServiceDesc(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ServiceDescription) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServiceDesc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ServiceDescription: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ServiceDescription: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExportId", wireType)
			}
			m.ExportId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceDesc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExportId |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceDesc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServiceDesc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceDesc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServiceDesc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateTs", wireType)
			}
			m.CreateTs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceDesc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreateTs |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000008)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Disabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceDesc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Disabled = bool(v != 0)
			hasFields[0] |= uint64(0x00000010)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToDelete", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceDesc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ToDelete = bool(v != 0)
			hasFields[0] |= uint64(0x00000020)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceDesc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServiceDesc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000040)
		default:
			iNdEx = preIndex
			skippy, err := skipServiceDesc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthServiceDesc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return proto.NewRequiredNotSetError("export_id")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return proto.NewRequiredNotSetError("s_type")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return proto.NewRequiredNotSetError("name")
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return proto.NewRequiredNotSetError("create_ts")
	}
	if hasFields[0]&uint64(0x00000010) == 0 {
		return proto.NewRequiredNotSetError("disabled")
	}
	if hasFields[0]&uint64(0x00000020) == 0 {
		return proto.NewRequiredNotSetError("to_delete")
	}
	if hasFields[0]&uint64(0x00000040) == 0 {
		return proto.NewRequiredNotSetError("service_id")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipServiceDesc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowServiceDesc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowServiceDesc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowServiceDesc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthServiceDesc
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowServiceDesc
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipServiceDesc(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthServiceDesc = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowServiceDesc   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("queue_info/service_desc.proto", fileDescriptorServiceDesc) }

var fileDescriptorServiceDesc = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcf, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x05, 0xe0, 0x38, 0x4d, 0xfb, 0x27, 0x1e, 0x3d, 0x59, 0xfa, 0xc5, 0xc5, 0xc0, 0x92, 0x01,
	0xc1, 0x3b, 0x54, 0x5d, 0xba, 0x42, 0x77, 0x2b, 0xc4, 0x17, 0xc9, 0x52, 0x89, 0x8d, 0xed, 0x22,
	0xba, 0xf1, 0x08, 0x3c, 0x06, 0x8f, 0xd2, 0xb1, 0x23, 0x13, 0x22, 0x66, 0x61, 0xec, 0xce, 0x82,
	0xda, 0x34, 0x22, 0xeb, 0x77, 0x8e, 0x8e, 0xee, 0xa5, 0x27, 0x8f, 0x2b, 0x5c, 0xa1, 0xd4, 0xcd,
	0xbd, 0xb9, 0xf6, 0xe8, 0x9e, 0x74, 0x8d, 0x52, 0xa1, 0xaf, 0xaf, 0xac, 0x33, 0xc1, 0x30, 0xfa,
	0x17, 0x9f, 0xff, 0x10, 0xca, 0x6e, 0xbb, 0xca, 0x0c, 0x7d, 0xed, 0xb4, 0x0d, 0xda, 0x34, 0xec,
	0x8c, 0x16, 0xf8, 0x6c, 0x8d, 0x0b, 0x52, 0x2b, 0x4e, 0x44, 0x5a, 0x66, 0xd3, 0x6c, 0xf3, 0x71,
	0x9a, 0xdc, 0xe4, 0x1d, 0xcf, 0x15, 0xfb, 0x4f, 0x27, 0x5e, 0x86, 0xb5, 0x45, 0x9e, 0x8a, 0xb4,
	0x2c, 0x8e, 0xf9, 0xd8, 0x2f, 0xd6, 0x16, 0x19, 0xa7, 0x59, 0x53, 0x3d, 0x20, 0x1f, 0x0d, 0xa2,
	0x83, 0xec, 0x97, 0x6b, 0x87, 0x55, 0x40, 0x19, 0x3c, 0xcf, 0x44, 0x5a, 0x8e, 0xfa, 0xe5, 0x8e,
	0x17, 0x9e, 0x09, 0x9a, 0x2b, 0xed, 0xab, 0xbb, 0x25, 0x2a, 0x3e, 0x16, 0x69, 0x99, 0xf7, 0x8d,
	0x5e, 0xf7, 0x23, 0xc1, 0x48, 0x85, 0x4b, 0x0c, 0xc8, 0x27, 0xc3, 0x4a, 0x30, 0xb3, 0x83, 0xb2,
	0x0b, 0x4a, 0xfb, 0xd7, 0xb5, 0xe2, 0xff, 0x06, 0x77, 0x14, 0x47, 0x9f, 0xab, 0xe9, 0xe5, 0xb6,
	0x85, 0xe4, 0xbd, 0x85, 0x64, 0xd7, 0x02, 0x79, 0x89, 0x40, 0xde, 0x22, 0x90, 0x4d, 0x04, 0xb2,
	0x8d, 0x40, 0x3e, 0x23, 0x90, 0xef, 0x08, 0xc9, 0x2e, 0x02, 0x79, 0xfd, 0x82, 0xe4, 0x37, 0x00,
	0x00, 0xff, 0xff, 0x51, 0xab, 0xca, 0x92, 0x57, 0x01, 0x00, 0x00,
}
