// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qconf/qconfig.proto

package qconf

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type QueueConfig struct {
	// Default message TTL.
	MsgTtl int64 `protobuf:"varint,1,opt,name=msg_ttl,json=msgTtl,proto3" json:"msg_ttl,omitempty"`
	// Default delivery delay.
	DeliveryDelay int64 `protobuf:"varint,2,opt,name=delivery_delay,json=deliveryDelay,proto3" json:"delivery_delay,omitempty"`
	// Timeout before message is getting released.
	PopLockTimeout int64 `protobuf:"varint,3,opt,name=pop_lock_timeout,json=popLockTimeout,proto3" json:"pop_lock_timeout,omitempty"`
	// Pop count limit. 0 - unlimited. >0 Will be removed after this number of attempts.
	PopCountLimit int64 `protobuf:"varint,4,opt,name=pop_count_limit,json=popCountLimit,proto3" json:"pop_count_limit,omitempty"`
	// Max queue size.
	MaxMsgsInQueue int64 `protobuf:"varint,5,opt,name=max_msgs_in_queue,json=maxMsgsInQueue,proto3" json:"max_msgs_in_queue,omitempty"`
	// Max message size in bytes;
	MaxMsgSize int64 `protobuf:"varint,6,opt,name=max_msg_size,json=maxMsgSize,proto3" json:"max_msg_size,omitempty"`
	// Last time item has been pushed into queue.
	LastPushTs int64 `protobuf:"varint,7,opt,name=last_push_ts,json=lastPushTs,proto3" json:"last_push_ts,omitempty"`
	// Last pop time.
	LastPopTs int64 `protobuf:"varint,8,opt,name=last_pop_ts,json=lastPopTs,proto3" json:"last_pop_ts,omitempty"`
	// Pop wait timeout.
	PopWaitTimeout int64 `protobuf:"varint,9,opt,name=pop_wait_timeout,json=popWaitTimeout,proto3" json:"pop_wait_timeout,omitempty"`
	// Messages exceeded number of pop attemts will be moved into this queue if configured
	PopLimitQueueName string `protobuf:"bytes,10,opt,name=pop_limit_queue_name,json=popLimitQueueName,proto3" json:"pop_limit_queue_name,omitempty"`
	// Time stamp config was modified last time.
	LastUpdateTs         int64    `protobuf:"varint,11,opt,name=last_update_ts,json=lastUpdateTs,proto3" json:"last_update_ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueConfig) Reset()         { *m = QueueConfig{} }
func (m *QueueConfig) String() string { return proto.CompactTextString(m) }
func (*QueueConfig) ProtoMessage()    {}
func (*QueueConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_qconfig_06056856dbf51587, []int{0}
}
func (m *QueueConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueueConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueueConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *QueueConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueConfig.Merge(dst, src)
}
func (m *QueueConfig) XXX_Size() int {
	return m.Size()
}
func (m *QueueConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueConfig.DiscardUnknown(m)
}

var xxx_messageInfo_QueueConfig proto.InternalMessageInfo

func (m *QueueConfig) GetMsgTtl() int64 {
	if m != nil {
		return m.MsgTtl
	}
	return 0
}

func (m *QueueConfig) GetDeliveryDelay() int64 {
	if m != nil {
		return m.DeliveryDelay
	}
	return 0
}

func (m *QueueConfig) GetPopLockTimeout() int64 {
	if m != nil {
		return m.PopLockTimeout
	}
	return 0
}

func (m *QueueConfig) GetPopCountLimit() int64 {
	if m != nil {
		return m.PopCountLimit
	}
	return 0
}

func (m *QueueConfig) GetMaxMsgsInQueue() int64 {
	if m != nil {
		return m.MaxMsgsInQueue
	}
	return 0
}

func (m *QueueConfig) GetMaxMsgSize() int64 {
	if m != nil {
		return m.MaxMsgSize
	}
	return 0
}

func (m *QueueConfig) GetLastPushTs() int64 {
	if m != nil {
		return m.LastPushTs
	}
	return 0
}

func (m *QueueConfig) GetLastPopTs() int64 {
	if m != nil {
		return m.LastPopTs
	}
	return 0
}

func (m *QueueConfig) GetPopWaitTimeout() int64 {
	if m != nil {
		return m.PopWaitTimeout
	}
	return 0
}

func (m *QueueConfig) GetPopLimitQueueName() string {
	if m != nil {
		return m.PopLimitQueueName
	}
	return ""
}

func (m *QueueConfig) GetLastUpdateTs() int64 {
	if m != nil {
		return m.LastUpdateTs
	}
	return 0
}

func init() {
	proto.RegisterType((*QueueConfig)(nil), "qconf.QueueConfig")
}
func (m *QueueConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueueConfig) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.MsgTtl != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintQconfig(dAtA, i, uint64(m.MsgTtl))
	}
	if m.DeliveryDelay != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintQconfig(dAtA, i, uint64(m.DeliveryDelay))
	}
	if m.PopLockTimeout != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintQconfig(dAtA, i, uint64(m.PopLockTimeout))
	}
	if m.PopCountLimit != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintQconfig(dAtA, i, uint64(m.PopCountLimit))
	}
	if m.MaxMsgsInQueue != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintQconfig(dAtA, i, uint64(m.MaxMsgsInQueue))
	}
	if m.MaxMsgSize != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintQconfig(dAtA, i, uint64(m.MaxMsgSize))
	}
	if m.LastPushTs != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintQconfig(dAtA, i, uint64(m.LastPushTs))
	}
	if m.LastPopTs != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintQconfig(dAtA, i, uint64(m.LastPopTs))
	}
	if m.PopWaitTimeout != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintQconfig(dAtA, i, uint64(m.PopWaitTimeout))
	}
	if len(m.PopLimitQueueName) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintQconfig(dAtA, i, uint64(len(m.PopLimitQueueName)))
		i += copy(dAtA[i:], m.PopLimitQueueName)
	}
	if m.LastUpdateTs != 0 {
		dAtA[i] = 0x58
		i++
		i = encodeVarintQconfig(dAtA, i, uint64(m.LastUpdateTs))
	}
	return i, nil
}

func encodeVarintQconfig(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *QueueConfig) Size() (n int) {
	var l int
	_ = l
	if m.MsgTtl != 0 {
		n += 1 + sovQconfig(uint64(m.MsgTtl))
	}
	if m.DeliveryDelay != 0 {
		n += 1 + sovQconfig(uint64(m.DeliveryDelay))
	}
	if m.PopLockTimeout != 0 {
		n += 1 + sovQconfig(uint64(m.PopLockTimeout))
	}
	if m.PopCountLimit != 0 {
		n += 1 + sovQconfig(uint64(m.PopCountLimit))
	}
	if m.MaxMsgsInQueue != 0 {
		n += 1 + sovQconfig(uint64(m.MaxMsgsInQueue))
	}
	if m.MaxMsgSize != 0 {
		n += 1 + sovQconfig(uint64(m.MaxMsgSize))
	}
	if m.LastPushTs != 0 {
		n += 1 + sovQconfig(uint64(m.LastPushTs))
	}
	if m.LastPopTs != 0 {
		n += 1 + sovQconfig(uint64(m.LastPopTs))
	}
	if m.PopWaitTimeout != 0 {
		n += 1 + sovQconfig(uint64(m.PopWaitTimeout))
	}
	l = len(m.PopLimitQueueName)
	if l > 0 {
		n += 1 + l + sovQconfig(uint64(l))
	}
	if m.LastUpdateTs != 0 {
		n += 1 + sovQconfig(uint64(m.LastUpdateTs))
	}
	return n
}

func sovQconfig(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozQconfig(x uint64) (n int) {
	return sovQconfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueueConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQconfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueueConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueueConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgTtl", wireType)
			}
			m.MsgTtl = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MsgTtl |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeliveryDelay", wireType)
			}
			m.DeliveryDelay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeliveryDelay |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PopLockTimeout", wireType)
			}
			m.PopLockTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PopLockTimeout |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PopCountLimit", wireType)
			}
			m.PopCountLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PopCountLimit |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMsgsInQueue", wireType)
			}
			m.MaxMsgsInQueue = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxMsgsInQueue |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMsgSize", wireType)
			}
			m.MaxMsgSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxMsgSize |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastPushTs", wireType)
			}
			m.LastPushTs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastPushTs |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastPopTs", wireType)
			}
			m.LastPopTs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastPopTs |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PopWaitTimeout", wireType)
			}
			m.PopWaitTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PopWaitTimeout |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PopLimitQueueName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQconfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PopLimitQueueName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdateTs", wireType)
			}
			m.LastUpdateTs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastUpdateTs |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQconfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQconfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQconfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQconfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQconfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQconfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthQconfig
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowQconfig
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipQconfig(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthQconfig = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQconfig   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("qconf/qconfig.proto", fileDescriptor_qconfig_06056856dbf51587) }

var fileDescriptor_qconfig_06056856dbf51587 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x91, 0xc1, 0x4e, 0x2a, 0x31,
	0x14, 0x86, 0xef, 0x5c, 0x2e, 0x70, 0x29, 0xf7, 0x22, 0x54, 0x13, 0xbb, 0x9a, 0x10, 0xa3, 0x06,
	0x37, 0xb2, 0xf0, 0x0d, 0xc4, 0x8d, 0x09, 0x1a, 0xc5, 0x31, 0x2e, 0x9b, 0x3a, 0xd4, 0xa1, 0x61,
	0x3a, 0x2d, 0x9c, 0x8e, 0x02, 0x4f, 0xe1, 0x9b, 0xf8, 0x1a, 0x2e, 0x7d, 0x04, 0x83, 0x2f, 0x62,
	0x7a, 0x2a, 0x6c, 0x26, 0x99, 0xef, 0x7c, 0x39, 0xfd, 0xff, 0x96, 0xec, 0xce, 0x52, 0x53, 0x3c,
	0xf5, 0xf1, 0xab, 0xb2, 0x53, 0x3b, 0x37, 0xce, 0xd0, 0x2a, 0xfe, 0x1e, 0xbc, 0x55, 0x48, 0xf3,
	0xb6, 0x94, 0xa5, 0x1c, 0xe0, 0x90, 0xee, 0x93, 0xba, 0x86, 0x8c, 0x3b, 0x97, 0xb3, 0xa8, 0x1b,
	0xf5, 0x2a, 0xa3, 0x9a, 0x86, 0x2c, 0x71, 0x39, 0x3d, 0x22, 0xad, 0xb1, 0xcc, 0xd5, 0xb3, 0x9c,
	0x2f, 0xf9, 0x58, 0xe6, 0x62, 0xc9, 0x7e, 0xe3, 0xfc, 0xff, 0x86, 0x5e, 0x78, 0x48, 0x7b, 0xa4,
	0x6d, 0x8d, 0xe5, 0xb9, 0x49, 0xa7, 0xdc, 0x29, 0x2d, 0x4d, 0xe9, 0x58, 0x05, 0xc5, 0x96, 0x35,
	0x76, 0x68, 0xd2, 0x69, 0x12, 0x28, 0x3d, 0x26, 0x3b, 0xde, 0x4c, 0x4d, 0x59, 0x38, 0x9e, 0x2b,
	0xad, 0x1c, 0xfb, 0x13, 0x36, 0x5a, 0x63, 0x07, 0x9e, 0x0e, 0x3d, 0xa4, 0x27, 0xa4, 0xa3, 0xc5,
	0x82, 0x6b, 0xc8, 0x80, 0xab, 0x82, 0xcf, 0x7c, 0x58, 0x56, 0x0d, 0x2b, 0xb5, 0x58, 0x5c, 0x41,
	0x06, 0x97, 0x05, 0x56, 0xa0, 0x5d, 0xf2, 0xef, 0x47, 0xe5, 0xa0, 0x56, 0x92, 0xd5, 0xd0, 0x22,
	0xc1, 0xba, 0x53, 0x2b, 0x34, 0x72, 0x01, 0x8e, 0xdb, 0x12, 0x26, 0xdc, 0x01, 0xab, 0x07, 0xc3,
	0xb3, 0x9b, 0x12, 0x26, 0x09, 0xd0, 0x98, 0x34, 0x83, 0x61, 0xac, 0x17, 0xfe, 0xa2, 0xd0, 0x40,
	0xc1, 0xd8, 0x04, 0x36, 0x05, 0x5f, 0x84, 0x72, 0xdb, 0x82, 0x8d, 0x6d, 0xc1, 0x07, 0xa1, 0xdc,
	0xa6, 0x60, 0x9f, 0xec, 0xe1, 0x55, 0xf8, 0x16, 0x21, 0x36, 0x2f, 0x84, 0x96, 0x8c, 0x74, 0xa3,
	0x5e, 0x63, 0xd4, 0xf1, 0xd7, 0xe1, 0x47, 0x18, 0xfd, 0x5a, 0x68, 0x49, 0x0f, 0x49, 0x0b, 0x8f,
	0x2e, 0xed, 0x58, 0x38, 0xe9, 0x4f, 0x6f, 0xe2, 0x62, 0x8c, 0x7c, 0x8f, 0x30, 0x81, 0xf3, 0xf6,
	0xfb, 0x3a, 0x8e, 0x3e, 0xd6, 0x71, 0xf4, 0xb9, 0x8e, 0xa3, 0xd7, 0xaf, 0xf8, 0xd7, 0x63, 0x0d,
	0x5f, 0xf4, 0xec, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x28, 0x73, 0x43, 0x1d, 0xe8, 0x01, 0x00, 0x00,
}
