// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: server/sqsproto/sqsmsg/sqspayload.proto

package sqsmsg

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type UserAttribute struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAttribute) Reset()         { *m = UserAttribute{} }
func (m *UserAttribute) String() string { return proto.CompactTextString(m) }
func (*UserAttribute) ProtoMessage()    {}
func (*UserAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_sqspayload_01b6b99b7f2342d2, []int{0}
}
func (m *UserAttribute) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserAttribute.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *UserAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAttribute.Merge(dst, src)
}
func (m *UserAttribute) XXX_Size() int {
	return m.Size()
}
func (m *UserAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_UserAttribute proto.InternalMessageInfo

func (m *UserAttribute) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UserAttribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SQSMessagePayload struct {
	Payload                string                    `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	MD5OfMessageBody       string                    `protobuf:"bytes,2,opt,name=MD5_of_message_body,json=MD5OfMessageBody,proto3" json:"MD5_of_message_body,omitempty"`
	MD5OfMessageAttributes string                    `protobuf:"bytes,3,opt,name=MD5_of_message_attributes,json=MD5OfMessageAttributes,proto3" json:"MD5_of_message_attributes,omitempty"`
	SenderId               string                    `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SentTimestamp          string                    `protobuf:"bytes,5,opt,name=sent_timestamp,json=sentTimestamp,proto3" json:"sent_timestamp,omitempty"`
	UserAttributes         map[string]*UserAttribute `protobuf:"bytes,6,rep,name=user_attributes,json=userAttributes" json:"user_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral   struct{}                  `json:"-"`
	XXX_sizecache          int32                     `json:"-"`
}

func (m *SQSMessagePayload) Reset()         { *m = SQSMessagePayload{} }
func (m *SQSMessagePayload) String() string { return proto.CompactTextString(m) }
func (*SQSMessagePayload) ProtoMessage()    {}
func (*SQSMessagePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_sqspayload_01b6b99b7f2342d2, []int{1}
}
func (m *SQSMessagePayload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SQSMessagePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SQSMessagePayload.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SQSMessagePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SQSMessagePayload.Merge(dst, src)
}
func (m *SQSMessagePayload) XXX_Size() int {
	return m.Size()
}
func (m *SQSMessagePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SQSMessagePayload.DiscardUnknown(m)
}

var xxx_messageInfo_SQSMessagePayload proto.InternalMessageInfo

func (m *SQSMessagePayload) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *SQSMessagePayload) GetMD5OfMessageBody() string {
	if m != nil {
		return m.MD5OfMessageBody
	}
	return ""
}

func (m *SQSMessagePayload) GetMD5OfMessageAttributes() string {
	if m != nil {
		return m.MD5OfMessageAttributes
	}
	return ""
}

func (m *SQSMessagePayload) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *SQSMessagePayload) GetSentTimestamp() string {
	if m != nil {
		return m.SentTimestamp
	}
	return ""
}

func (m *SQSMessagePayload) GetUserAttributes() map[string]*UserAttribute {
	if m != nil {
		return m.UserAttributes
	}
	return nil
}

func init() {
	proto.RegisterType((*UserAttribute)(nil), "sqsmsg.UserAttribute")
	proto.RegisterType((*SQSMessagePayload)(nil), "sqsmsg.SQSMessagePayload")
	proto.RegisterMapType((map[string]*UserAttribute)(nil), "sqsmsg.SQSMessagePayload.UserAttributesEntry")
}
func (m *UserAttribute) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserAttribute) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Type) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSqspayload(dAtA, i, uint64(len(m.Type)))
		i += copy(dAtA[i:], m.Type)
	}
	if len(m.Value) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintSqspayload(dAtA, i, uint64(len(m.Value)))
		i += copy(dAtA[i:], m.Value)
	}
	return i, nil
}

func (m *SQSMessagePayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SQSMessagePayload) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Payload) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSqspayload(dAtA, i, uint64(len(m.Payload)))
		i += copy(dAtA[i:], m.Payload)
	}
	if len(m.MD5OfMessageBody) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintSqspayload(dAtA, i, uint64(len(m.MD5OfMessageBody)))
		i += copy(dAtA[i:], m.MD5OfMessageBody)
	}
	if len(m.MD5OfMessageAttributes) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintSqspayload(dAtA, i, uint64(len(m.MD5OfMessageAttributes)))
		i += copy(dAtA[i:], m.MD5OfMessageAttributes)
	}
	if len(m.SenderId) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintSqspayload(dAtA, i, uint64(len(m.SenderId)))
		i += copy(dAtA[i:], m.SenderId)
	}
	if len(m.SentTimestamp) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintSqspayload(dAtA, i, uint64(len(m.SentTimestamp)))
		i += copy(dAtA[i:], m.SentTimestamp)
	}
	if len(m.UserAttributes) > 0 {
		for k, _ := range m.UserAttributes {
			dAtA[i] = 0x32
			i++
			v := m.UserAttributes[k]
			msgSize := 0
			if v != nil {
				msgSize = v.Size()
				msgSize += 1 + sovSqspayload(uint64(msgSize))
			}
			mapSize := 1 + len(k) + sovSqspayload(uint64(len(k))) + msgSize
			i = encodeVarintSqspayload(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintSqspayload(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			if v != nil {
				dAtA[i] = 0x12
				i++
				i = encodeVarintSqspayload(dAtA, i, uint64(v.Size()))
				n1, err := v.MarshalTo(dAtA[i:])
				if err != nil {
					return 0, err
				}
				i += n1
			}
		}
	}
	return i, nil
}

func encodeVarintSqspayload(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *UserAttribute) Size() (n int) {
	var l int
	_ = l
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovSqspayload(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovSqspayload(uint64(l))
	}
	return n
}

func (m *SQSMessagePayload) Size() (n int) {
	var l int
	_ = l
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovSqspayload(uint64(l))
	}
	l = len(m.MD5OfMessageBody)
	if l > 0 {
		n += 1 + l + sovSqspayload(uint64(l))
	}
	l = len(m.MD5OfMessageAttributes)
	if l > 0 {
		n += 1 + l + sovSqspayload(uint64(l))
	}
	l = len(m.SenderId)
	if l > 0 {
		n += 1 + l + sovSqspayload(uint64(l))
	}
	l = len(m.SentTimestamp)
	if l > 0 {
		n += 1 + l + sovSqspayload(uint64(l))
	}
	if len(m.UserAttributes) > 0 {
		for k, v := range m.UserAttributes {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovSqspayload(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovSqspayload(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovSqspayload(uint64(mapEntrySize))
		}
	}
	return n
}

func sovSqspayload(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozSqspayload(x uint64) (n int) {
	return sovSqspayload(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UserAttribute) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSqspayload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserAttribute: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserAttribute: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSqspayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSqspayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSqspayload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSqspayload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SQSMessagePayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSqspayload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SQSMessagePayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SQSMessagePayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSqspayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MD5OfMessageBody", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSqspayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MD5OfMessageBody = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MD5OfMessageAttributes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSqspayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MD5OfMessageAttributes = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSqspayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SenderId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SentTimestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSqspayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SentTimestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserAttributes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSqspayload
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UserAttributes == nil {
				m.UserAttributes = make(map[string]*UserAttribute)
			}
			var mapkey string
			var mapvalue *UserAttribute
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSqspayload
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSqspayload
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthSqspayload
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSqspayload
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= (int(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthSqspayload
					}
					postmsgIndex := iNdEx + mapmsglen
					if mapmsglen < 0 {
						return ErrInvalidLengthSqspayload
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &UserAttribute{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipSqspayload(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthSqspayload
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.UserAttributes[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSqspayload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSqspayload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSqspayload(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSqspayload
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthSqspayload
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowSqspayload
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipSqspayload(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthSqspayload = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSqspayload   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("server/sqsproto/sqsmsg/sqspayload.proto", fileDescriptor_sqspayload_01b6b99b7f2342d2)
}

var fileDescriptor_sqspayload_01b6b99b7f2342d2 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x51, 0x4b, 0x32, 0x51,
	0x10, 0xfd, 0xd6, 0x55, 0xbf, 0x1c, 0xd1, 0x6c, 0xac, 0xd8, 0x0a, 0x16, 0x11, 0x22, 0x21, 0xdc,
	0xc0, 0x10, 0xb2, 0xb7, 0xc4, 0x1e, 0x7a, 0x90, 0x4a, 0x2b, 0x7a, 0x5b, 0x56, 0x76, 0x14, 0xc9,
	0x75, 0xed, 0xce, 0x5d, 0x61, 0x7f, 0x44, 0xd0, 0xcf, 0xea, 0xb1, 0x9f, 0x10, 0xf6, 0x47, 0xc2,
	0xbb, 0xbb, 0xa1, 0xd5, 0xdb, 0xcc, 0xb9, 0xe7, 0x9c, 0xb9, 0x73, 0x06, 0x8e, 0x98, 0xc4, 0x9c,
	0xc4, 0x09, 0x3f, 0xf3, 0x4c, 0xf8, 0xd2, 0x5f, 0x16, 0x1e, 0x8f, 0x54, 0xef, 0x84, 0x13, 0xdf,
	0x71, 0x2d, 0x85, 0x63, 0x36, 0x7a, 0xa8, 0xb6, 0xa0, 0x70, 0xcf, 0x24, 0x2e, 0xa4, 0x14, 0xe3,
	0x41, 0x20, 0x09, 0x11, 0xd2, 0x32, 0x9c, 0x91, 0xa1, 0x55, 0xb4, 0x5a, 0xae, 0xa7, 0x6a, 0xdc,
	0x86, 0xcc, 0xdc, 0x99, 0x04, 0x64, 0xa4, 0x14, 0x18, 0x35, 0xd5, 0x17, 0x1d, 0xb6, 0xfa, 0xb7,
	0xfd, 0x2e, 0x31, 0x3b, 0x23, 0xba, 0x89, 0xec, 0xd1, 0x80, 0xff, 0xf1, 0xa4, 0xd8, 0x22, 0x69,
	0xb1, 0x0e, 0xe5, 0x6e, 0xa7, 0x69, 0xfb, 0x43, 0xdb, 0x8b, 0x24, 0xf6, 0xc0, 0x77, 0xc3, 0xd8,
	0xb3, 0xd4, 0xed, 0x34, 0xaf, 0x87, 0xb1, 0x57, 0xdb, 0x77, 0x43, 0x6c, 0xc1, 0xde, 0x0f, 0xba,
	0x93, 0x7c, 0x92, 0x0d, 0x5d, 0x89, 0x76, 0x57, 0x45, 0xdf, 0x2b, 0x30, 0x1e, 0x40, 0x8e, 0x69,
	0xea, 0x92, 0xb0, 0xc7, 0xae, 0x91, 0x56, 0xd4, 0x8d, 0x08, 0xb8, 0x72, 0xf1, 0x10, 0x8a, 0x4c,
	0x53, 0x69, 0xcb, 0xb1, 0x47, 0x2c, 0x1d, 0x6f, 0x66, 0x64, 0x14, 0xa3, 0xb0, 0x44, 0xef, 0x12,
	0x10, 0x1f, 0x60, 0x33, 0x60, 0x12, 0xab, 0x43, 0xb3, 0x15, 0xbd, 0x96, 0x6f, 0xd4, 0xad, 0x28,
	0x3a, 0xeb, 0xd7, 0xee, 0xd6, 0x5a, 0x92, 0x7c, 0x39, 0x95, 0x22, 0xec, 0x15, 0x83, 0x35, 0x70,
	0xff, 0x11, 0xca, 0x7f, 0xd0, 0xb0, 0x04, 0xfa, 0x13, 0x85, 0x71, 0x64, 0xcb, 0x12, 0x8f, 0x57,
	0x43, 0xcf, 0x37, 0x76, 0x92, 0xb1, 0x6b, 0xea, 0xf8, 0x16, 0xe7, 0xa9, 0x33, 0xad, 0x5d, 0x7a,
	0x5b, 0x98, 0xda, 0xfb, 0xc2, 0xd4, 0x3e, 0x16, 0xa6, 0xf6, 0xfa, 0x69, 0xfe, 0x1b, 0x64, 0xd5,
	0xad, 0x4f, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x72, 0xe7, 0xe4, 0xda, 0x16, 0x02, 0x00, 0x00,
}
