// Code generated by protoc-gen-gogo.
// source: server/sqsproto/sqsmsg/sqspayload.proto
// DO NOT EDIT!

/*
	Package sqsmsg is a generated protocol buffer package.

	It is generated from these files:
		server/sqsproto/sqsmsg/sqspayload.proto

	It has these top-level messages:
		UserAttribute
		SQSMessagePayload
*/
package sqsmsg

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import strings "strings"
import github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"
import sort "sort"
import strconv "strconv"
import reflect "reflect"
import github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"

import errors "errors"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.GoGoProtoPackageIsVersion1

type UserAttribute struct {
	Type  string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *UserAttribute) Reset()                    { *m = UserAttribute{} }
func (*UserAttribute) ProtoMessage()               {}
func (*UserAttribute) Descriptor() ([]byte, []int) { return fileDescriptorSqspayload, []int{0} }

type SQSMessagePayload struct {
	Payload                string                    `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	MD5OfMessageBody       string                    `protobuf:"bytes,2,opt,name=MD5_of_message_body,json=mD5OfMessageBody,proto3" json:"MD5_of_message_body,omitempty"`
	MD5OfMessageAttributes string                    `protobuf:"bytes,3,opt,name=MD5_of_message_attributes,json=mD5OfMessageAttributes,proto3" json:"MD5_of_message_attributes,omitempty"`
	SenderId               string                    `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SentTimestamp          string                    `protobuf:"bytes,5,opt,name=sent_timestamp,json=sentTimestamp,proto3" json:"sent_timestamp,omitempty"`
	UserAttributes         map[string]*UserAttribute `protobuf:"bytes,6,rep,name=user_attributes,json=userAttributes" json:"user_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *SQSMessagePayload) Reset()                    { *m = SQSMessagePayload{} }
func (*SQSMessagePayload) ProtoMessage()               {}
func (*SQSMessagePayload) Descriptor() ([]byte, []int) { return fileDescriptorSqspayload, []int{1} }

func (m *SQSMessagePayload) GetUserAttributes() map[string]*UserAttribute {
	if m != nil {
		return m.UserAttributes
	}
	return nil
}

func init() {
	proto.RegisterType((*UserAttribute)(nil), "sqsmsg.UserAttribute")
	proto.RegisterType((*SQSMessagePayload)(nil), "sqsmsg.SQSMessagePayload")
}
func (this *UserAttribute) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*UserAttribute)
	if !ok {
		that2, ok := that.(UserAttribute)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	return true
}
func (this *SQSMessagePayload) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SQSMessagePayload)
	if !ok {
		that2, ok := that.(SQSMessagePayload)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Payload != that1.Payload {
		return false
	}
	if this.MD5OfMessageBody != that1.MD5OfMessageBody {
		return false
	}
	if this.MD5OfMessageAttributes != that1.MD5OfMessageAttributes {
		return false
	}
	if this.SenderId != that1.SenderId {
		return false
	}
	if this.SentTimestamp != that1.SentTimestamp {
		return false
	}
	if len(this.UserAttributes) != len(that1.UserAttributes) {
		return false
	}
	for i := range this.UserAttributes {
		if !this.UserAttributes[i].Equal(that1.UserAttributes[i]) {
			return false
		}
	}
	return true
}
func (this *UserAttribute) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&sqsmsg.UserAttribute{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Value: "+fmt.Sprintf("%#v", this.Value)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SQSMessagePayload) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&sqsmsg.SQSMessagePayload{")
	s = append(s, "Payload: "+fmt.Sprintf("%#v", this.Payload)+",\n")
	s = append(s, "MD5OfMessageBody: "+fmt.Sprintf("%#v", this.MD5OfMessageBody)+",\n")
	s = append(s, "MD5OfMessageAttributes: "+fmt.Sprintf("%#v", this.MD5OfMessageAttributes)+",\n")
	s = append(s, "SenderId: "+fmt.Sprintf("%#v", this.SenderId)+",\n")
	s = append(s, "SentTimestamp: "+fmt.Sprintf("%#v", this.SentTimestamp)+",\n")
	keysForUserAttributes := make([]string, 0, len(this.UserAttributes))
	for k, _ := range this.UserAttributes {
		keysForUserAttributes = append(keysForUserAttributes, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForUserAttributes)
	mapStringForUserAttributes := "map[string]*UserAttribute{"
	for _, k := range keysForUserAttributes {
		mapStringForUserAttributes += fmt.Sprintf("%#v: %#v,", k, this.UserAttributes[k])
	}
	mapStringForUserAttributes += "}"
	if this.UserAttributes != nil {
		s = append(s, "UserAttributes: "+mapStringForUserAttributes+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringSqspayload(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func extensionToGoStringSqspayload(e map[int32]github_com_gogo_protobuf_proto.Extension) string {
	if e == nil {
		return "nil"
	}
	s := "map[int32]proto.Extension{"
	keys := make([]int, 0, len(e))
	for k := range e {
		keys = append(keys, int(k))
	}
	sort.Ints(keys)
	ss := []string{}
	for _, k := range keys {
		ss = append(ss, strconv.Itoa(k)+": "+e[int32(k)].GoString())
	}
	s += strings.Join(ss, ",") + "}"
	return s
}
func (m *UserAttribute) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *UserAttribute) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Type) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintSqspayload(data, i, uint64(len(m.Type)))
		i += copy(data[i:], m.Type)
	}
	if len(m.Value) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintSqspayload(data, i, uint64(len(m.Value)))
		i += copy(data[i:], m.Value)
	}
	return i, nil
}

func (m *SQSMessagePayload) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *SQSMessagePayload) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Payload) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintSqspayload(data, i, uint64(len(m.Payload)))
		i += copy(data[i:], m.Payload)
	}
	if len(m.MD5OfMessageBody) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintSqspayload(data, i, uint64(len(m.MD5OfMessageBody)))
		i += copy(data[i:], m.MD5OfMessageBody)
	}
	if len(m.MD5OfMessageAttributes) > 0 {
		data[i] = 0x1a
		i++
		i = encodeVarintSqspayload(data, i, uint64(len(m.MD5OfMessageAttributes)))
		i += copy(data[i:], m.MD5OfMessageAttributes)
	}
	if len(m.SenderId) > 0 {
		data[i] = 0x22
		i++
		i = encodeVarintSqspayload(data, i, uint64(len(m.SenderId)))
		i += copy(data[i:], m.SenderId)
	}
	if len(m.SentTimestamp) > 0 {
		data[i] = 0x2a
		i++
		i = encodeVarintSqspayload(data, i, uint64(len(m.SentTimestamp)))
		i += copy(data[i:], m.SentTimestamp)
	}
	if len(m.UserAttributes) > 0 {
		for k, _ := range m.UserAttributes {
			data[i] = 0x32
			i++
			v := m.UserAttributes[k]
			if v == nil {
				return 0, errors.New("proto: map has nil element")
			}
			msgSize := v.Size()
			mapSize := 1 + len(k) + sovSqspayload(uint64(len(k))) + 1 + msgSize + sovSqspayload(uint64(msgSize))
			i = encodeVarintSqspayload(data, i, uint64(mapSize))
			data[i] = 0xa
			i++
			i = encodeVarintSqspayload(data, i, uint64(len(k)))
			i += copy(data[i:], k)
			data[i] = 0x12
			i++
			i = encodeVarintSqspayload(data, i, uint64(v.Size()))
			n1, err := v.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n1
		}
	}
	return i, nil
}

func encodeFixed64Sqspayload(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Sqspayload(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintSqspayload(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *UserAttribute) Size() (n int) {
	var l int
	_ = l
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovSqspayload(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovSqspayload(uint64(l))
	}
	return n
}

func (m *SQSMessagePayload) Size() (n int) {
	var l int
	_ = l
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovSqspayload(uint64(l))
	}
	l = len(m.MD5OfMessageBody)
	if l > 0 {
		n += 1 + l + sovSqspayload(uint64(l))
	}
	l = len(m.MD5OfMessageAttributes)
	if l > 0 {
		n += 1 + l + sovSqspayload(uint64(l))
	}
	l = len(m.SenderId)
	if l > 0 {
		n += 1 + l + sovSqspayload(uint64(l))
	}
	l = len(m.SentTimestamp)
	if l > 0 {
		n += 1 + l + sovSqspayload(uint64(l))
	}
	if len(m.UserAttributes) > 0 {
		for k, v := range m.UserAttributes {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
			}
			mapEntrySize := 1 + len(k) + sovSqspayload(uint64(len(k))) + 1 + l + sovSqspayload(uint64(l))
			n += mapEntrySize + 1 + sovSqspayload(uint64(mapEntrySize))
		}
	}
	return n
}

func sovSqspayload(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozSqspayload(x uint64) (n int) {
	return sovSqspayload(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *UserAttribute) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UserAttribute{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Value:` + fmt.Sprintf("%v", this.Value) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SQSMessagePayload) String() string {
	if this == nil {
		return "nil"
	}
	keysForUserAttributes := make([]string, 0, len(this.UserAttributes))
	for k, _ := range this.UserAttributes {
		keysForUserAttributes = append(keysForUserAttributes, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForUserAttributes)
	mapStringForUserAttributes := "map[string]*UserAttribute{"
	for _, k := range keysForUserAttributes {
		mapStringForUserAttributes += fmt.Sprintf("%v: %v,", k, this.UserAttributes[k])
	}
	mapStringForUserAttributes += "}"
	s := strings.Join([]string{`&SQSMessagePayload{`,
		`Payload:` + fmt.Sprintf("%v", this.Payload) + `,`,
		`MD5OfMessageBody:` + fmt.Sprintf("%v", this.MD5OfMessageBody) + `,`,
		`MD5OfMessageAttributes:` + fmt.Sprintf("%v", this.MD5OfMessageAttributes) + `,`,
		`SenderId:` + fmt.Sprintf("%v", this.SenderId) + `,`,
		`SentTimestamp:` + fmt.Sprintf("%v", this.SentTimestamp) + `,`,
		`UserAttributes:` + mapStringForUserAttributes + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringSqspayload(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *UserAttribute) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSqspayload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserAttribute: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserAttribute: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSqspayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSqspayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSqspayload(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSqspayload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SQSMessagePayload) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSqspayload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SQSMessagePayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SQSMessagePayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSqspayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MD5OfMessageBody", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSqspayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MD5OfMessageBody = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MD5OfMessageAttributes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSqspayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MD5OfMessageAttributes = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSqspayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SenderId = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SentTimestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSqspayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SentTimestamp = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserAttributes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSqspayload
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var keykey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				keykey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var stringLenmapkey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLenmapkey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLenmapkey := int(stringLenmapkey)
			if intStringLenmapkey < 0 {
				return ErrInvalidLengthSqspayload
			}
			postStringIndexmapkey := iNdEx + intStringLenmapkey
			if postStringIndexmapkey > l {
				return io.ErrUnexpectedEOF
			}
			mapkey := string(data[iNdEx:postStringIndexmapkey])
			iNdEx = postStringIndexmapkey
			var valuekey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				valuekey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var mapmsglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				mapmsglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if mapmsglen < 0 {
				return ErrInvalidLengthSqspayload
			}
			postmsgIndex := iNdEx + mapmsglen
			if mapmsglen < 0 {
				return ErrInvalidLengthSqspayload
			}
			if postmsgIndex > l {
				return io.ErrUnexpectedEOF
			}
			mapvalue := &UserAttribute{}
			if err := mapvalue.Unmarshal(data[iNdEx:postmsgIndex]); err != nil {
				return err
			}
			iNdEx = postmsgIndex
			if m.UserAttributes == nil {
				m.UserAttributes = make(map[string]*UserAttribute)
			}
			m.UserAttributes[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSqspayload(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSqspayload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSqspayload(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSqspayload
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSqspayload
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthSqspayload
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowSqspayload
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipSqspayload(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthSqspayload = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSqspayload   = fmt.Errorf("proto: integer overflow")
)

var fileDescriptorSqspayload = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x52, 0x2f, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2f, 0x2e, 0x2c, 0x2e, 0x28, 0xca, 0x2f, 0xc9, 0x07, 0x31, 0x72, 0x8b, 0xd3,
	0xc1, 0xfc, 0xc4, 0xca, 0x9c, 0xfc, 0xc4, 0x14, 0x3d, 0xb0, 0xb8, 0x10, 0x1b, 0x44, 0x42, 0xc9,
	0x92, 0x8b, 0x37, 0x14, 0xa8, 0xc7, 0xb1, 0xa4, 0xa4, 0x28, 0x33, 0xa9, 0xb4, 0x24, 0x55, 0x48,
	0x88, 0x8b, 0xa5, 0xa4, 0xb2, 0x20, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16,
	0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x02, 0x0b, 0x42, 0x38, 0x4a, 0xbd,
	0xcc, 0x5c, 0x82, 0xc1, 0x81, 0xc1, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x01, 0x10, 0xe3,
	0x85, 0x24, 0xb8, 0xd8, 0xa1, 0x36, 0x41, 0x8d, 0x80, 0x71, 0x85, 0x74, 0xb9, 0x84, 0x7d, 0x5d,
	0x4c, 0xe3, 0xf3, 0xd3, 0xe2, 0x73, 0x21, 0x5a, 0xe2, 0x93, 0xf2, 0x53, 0x2a, 0xa1, 0x66, 0x0a,
	0xe4, 0xba, 0x98, 0xfa, 0xa7, 0x41, 0xcd, 0x72, 0x02, 0x8a, 0x0b, 0x59, 0x72, 0x49, 0xa2, 0x29,
	0x4f, 0x84, 0x39, 0xb2, 0x58, 0x82, 0x19, 0xac, 0x49, 0x0c, 0x59, 0x13, 0xdc, 0x0b, 0xc5, 0x42,
	0xd2, 0x5c, 0x9c, 0xc5, 0xa9, 0x79, 0x29, 0xa9, 0x45, 0xf1, 0x99, 0x29, 0x12, 0x2c, 0x60, 0xa5,
	0x1c, 0x10, 0x01, 0xcf, 0x14, 0x21, 0x55, 0x2e, 0x3e, 0x20, 0xbb, 0x24, 0xbe, 0x24, 0x13, 0x68,
	0x6e, 0x49, 0x62, 0x6e, 0x81, 0x04, 0x2b, 0x58, 0x05, 0x2f, 0x48, 0x34, 0x04, 0x26, 0x28, 0x14,
	0xc6, 0xc5, 0x5f, 0x0a, 0x0c, 0x18, 0x64, 0x4b, 0xd9, 0x14, 0x98, 0x35, 0xb8, 0x8d, 0x74, 0xf5,
	0x20, 0x41, 0xa7, 0x87, 0xe1, 0x77, 0x3d, 0x94, 0x90, 0x2c, 0x76, 0xcd, 0x2b, 0x29, 0xaa, 0x0c,
	0xe2, 0x2b, 0x45, 0x11, 0x94, 0x8a, 0xe0, 0x12, 0xc6, 0xa2, 0x4c, 0x48, 0x80, 0x8b, 0x39, 0x3b,
	0xb5, 0x12, 0x1a, 0x64, 0x20, 0xa6, 0x90, 0x36, 0x72, 0xa0, 0x73, 0x1b, 0x89, 0xc2, 0xac, 0x45,
	0xd1, 0x0d, 0x8d, 0x0b, 0x2b, 0x26, 0x0b, 0x46, 0x27, 0x9d, 0x0b, 0x0f, 0xe5, 0x18, 0x6e, 0x00,
	0xf1, 0x87, 0x87, 0x72, 0x8c, 0x0d, 0x8f, 0xe4, 0x18, 0x57, 0x00, 0xf1, 0x09, 0x20, 0xbe, 0x00,
	0xc4, 0x0f, 0x80, 0xf8, 0xc5, 0x23, 0xa0, 0x1c, 0x90, 0x9e, 0xf0, 0x58, 0x8e, 0x21, 0x89, 0x0d,
	0x9c, 0x0e, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xce, 0x9a, 0x42, 0x9c, 0x32, 0x02, 0x00,
	0x00,
}
