// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: server/snsproto/dbdata/topic_data.proto

/*
	Package dbdata is a generated protocol buffer package.

	It is generated from these files:
		server/snsproto/dbdata/topic_data.proto

	It has these top-level messages:
		Subscription
		Topic
		TopicNames
*/
package dbdata

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import strings "strings"
import reflect "reflect"
import sortkeys "github.com/gogo/protobuf/sortkeys"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Subscription struct {
	Arn         string `protobuf:"bytes,1,opt,name=arn,proto3" json:"arn,omitempty"`
	Owner       string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Endpoint    string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Protocol    string `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	RawDelivery bool   `protobuf:"varint,5,opt,name=raw_delivery,json=rawDelivery,proto3" json:"raw_delivery,omitempty"`
	Pending     bool   `protobuf:"varint,6,opt,name=pending,proto3" json:"pending,omitempty"`
}

func (m *Subscription) Reset()                    { *m = Subscription{} }
func (*Subscription) ProtoMessage()               {}
func (*Subscription) Descriptor() ([]byte, []int) { return fileDescriptorTopicData, []int{0} }

func (m *Subscription) GetArn() string {
	if m != nil {
		return m.Arn
	}
	return ""
}

func (m *Subscription) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Subscription) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Subscription) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Subscription) GetRawDelivery() bool {
	if m != nil {
		return m.RawDelivery
	}
	return false
}

func (m *Subscription) GetPending() bool {
	if m != nil {
		return m.Pending
	}
	return false
}

type Topic struct {
	Arn                     string                   `protobuf:"bytes,1,opt,name=arn,proto3" json:"arn,omitempty"`
	Name                    string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName             string                   `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Policy                  string                   `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	DeliveryPolicy          string                   `protobuf:"bytes,5,opt,name=delivery_policy,json=deliveryPolicy,proto3" json:"delivery_policy,omitempty"`
	EffectiveDeliveryPolicy string                   `protobuf:"bytes,6,opt,name=effective_delivery_policy,json=effectiveDeliveryPolicy,proto3" json:"effective_delivery_policy,omitempty"`
	DeletedSubscriptions    int64                    `protobuf:"varint,7,opt,name=deleted_subscriptions,json=deletedSubscriptions,proto3" json:"deleted_subscriptions,omitempty"`
	SqsSubscriptions        map[string]*Subscription `protobuf:"bytes,8,rep,name=sqs_subscriptions,json=sqsSubscriptions" json:"sqs_subscriptions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	OtherSubscriptions      map[string]*Subscription `protobuf:"bytes,9,rep,name=other_subscriptions,json=otherSubscriptions" json:"other_subscriptions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Topic) Reset()                    { *m = Topic{} }
func (*Topic) ProtoMessage()               {}
func (*Topic) Descriptor() ([]byte, []int) { return fileDescriptorTopicData, []int{1} }

func (m *Topic) GetArn() string {
	if m != nil {
		return m.Arn
	}
	return ""
}

func (m *Topic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Topic) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Topic) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

func (m *Topic) GetDeliveryPolicy() string {
	if m != nil {
		return m.DeliveryPolicy
	}
	return ""
}

func (m *Topic) GetEffectiveDeliveryPolicy() string {
	if m != nil {
		return m.EffectiveDeliveryPolicy
	}
	return ""
}

func (m *Topic) GetDeletedSubscriptions() int64 {
	if m != nil {
		return m.DeletedSubscriptions
	}
	return 0
}

func (m *Topic) GetSqsSubscriptions() map[string]*Subscription {
	if m != nil {
		return m.SqsSubscriptions
	}
	return nil
}

func (m *Topic) GetOtherSubscriptions() map[string]*Subscription {
	if m != nil {
		return m.OtherSubscriptions
	}
	return nil
}

type TopicNames struct {
	Topics []string `protobuf:"bytes,1,rep,name=topics" json:"topics,omitempty"`
}

func (m *TopicNames) Reset()                    { *m = TopicNames{} }
func (*TopicNames) ProtoMessage()               {}
func (*TopicNames) Descriptor() ([]byte, []int) { return fileDescriptorTopicData, []int{2} }

func (m *TopicNames) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

func init() {
	proto.RegisterType((*Subscription)(nil), "dbdata.Subscription")
	proto.RegisterType((*Topic)(nil), "dbdata.Topic")
	proto.RegisterType((*TopicNames)(nil), "dbdata.TopicNames")
}
func (this *Subscription) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Subscription)
	if !ok {
		that2, ok := that.(Subscription)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Arn != that1.Arn {
		return false
	}
	if this.Owner != that1.Owner {
		return false
	}
	if this.Endpoint != that1.Endpoint {
		return false
	}
	if this.Protocol != that1.Protocol {
		return false
	}
	if this.RawDelivery != that1.RawDelivery {
		return false
	}
	if this.Pending != that1.Pending {
		return false
	}
	return true
}
func (this *Topic) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Topic)
	if !ok {
		that2, ok := that.(Topic)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Arn != that1.Arn {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.DisplayName != that1.DisplayName {
		return false
	}
	if this.Policy != that1.Policy {
		return false
	}
	if this.DeliveryPolicy != that1.DeliveryPolicy {
		return false
	}
	if this.EffectiveDeliveryPolicy != that1.EffectiveDeliveryPolicy {
		return false
	}
	if this.DeletedSubscriptions != that1.DeletedSubscriptions {
		return false
	}
	if len(this.SqsSubscriptions) != len(that1.SqsSubscriptions) {
		return false
	}
	for i := range this.SqsSubscriptions {
		if !this.SqsSubscriptions[i].Equal(that1.SqsSubscriptions[i]) {
			return false
		}
	}
	if len(this.OtherSubscriptions) != len(that1.OtherSubscriptions) {
		return false
	}
	for i := range this.OtherSubscriptions {
		if !this.OtherSubscriptions[i].Equal(that1.OtherSubscriptions[i]) {
			return false
		}
	}
	return true
}
func (this *TopicNames) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TopicNames)
	if !ok {
		that2, ok := that.(TopicNames)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Topics) != len(that1.Topics) {
		return false
	}
	for i := range this.Topics {
		if this.Topics[i] != that1.Topics[i] {
			return false
		}
	}
	return true
}
func (this *Subscription) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&dbdata.Subscription{")
	s = append(s, "Arn: "+fmt.Sprintf("%#v", this.Arn)+",\n")
	s = append(s, "Owner: "+fmt.Sprintf("%#v", this.Owner)+",\n")
	s = append(s, "Endpoint: "+fmt.Sprintf("%#v", this.Endpoint)+",\n")
	s = append(s, "Protocol: "+fmt.Sprintf("%#v", this.Protocol)+",\n")
	s = append(s, "RawDelivery: "+fmt.Sprintf("%#v", this.RawDelivery)+",\n")
	s = append(s, "Pending: "+fmt.Sprintf("%#v", this.Pending)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Topic) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 13)
	s = append(s, "&dbdata.Topic{")
	s = append(s, "Arn: "+fmt.Sprintf("%#v", this.Arn)+",\n")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "DisplayName: "+fmt.Sprintf("%#v", this.DisplayName)+",\n")
	s = append(s, "Policy: "+fmt.Sprintf("%#v", this.Policy)+",\n")
	s = append(s, "DeliveryPolicy: "+fmt.Sprintf("%#v", this.DeliveryPolicy)+",\n")
	s = append(s, "EffectiveDeliveryPolicy: "+fmt.Sprintf("%#v", this.EffectiveDeliveryPolicy)+",\n")
	s = append(s, "DeletedSubscriptions: "+fmt.Sprintf("%#v", this.DeletedSubscriptions)+",\n")
	keysForSqsSubscriptions := make([]string, 0, len(this.SqsSubscriptions))
	for k, _ := range this.SqsSubscriptions {
		keysForSqsSubscriptions = append(keysForSqsSubscriptions, k)
	}
	sortkeys.Strings(keysForSqsSubscriptions)
	mapStringForSqsSubscriptions := "map[string]*Subscription{"
	for _, k := range keysForSqsSubscriptions {
		mapStringForSqsSubscriptions += fmt.Sprintf("%#v: %#v,", k, this.SqsSubscriptions[k])
	}
	mapStringForSqsSubscriptions += "}"
	if this.SqsSubscriptions != nil {
		s = append(s, "SqsSubscriptions: "+mapStringForSqsSubscriptions+",\n")
	}
	keysForOtherSubscriptions := make([]string, 0, len(this.OtherSubscriptions))
	for k, _ := range this.OtherSubscriptions {
		keysForOtherSubscriptions = append(keysForOtherSubscriptions, k)
	}
	sortkeys.Strings(keysForOtherSubscriptions)
	mapStringForOtherSubscriptions := "map[string]*Subscription{"
	for _, k := range keysForOtherSubscriptions {
		mapStringForOtherSubscriptions += fmt.Sprintf("%#v: %#v,", k, this.OtherSubscriptions[k])
	}
	mapStringForOtherSubscriptions += "}"
	if this.OtherSubscriptions != nil {
		s = append(s, "OtherSubscriptions: "+mapStringForOtherSubscriptions+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TopicNames) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&dbdata.TopicNames{")
	s = append(s, "Topics: "+fmt.Sprintf("%#v", this.Topics)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringTopicData(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Subscription) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Subscription) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Arn) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTopicData(dAtA, i, uint64(len(m.Arn)))
		i += copy(dAtA[i:], m.Arn)
	}
	if len(m.Owner) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTopicData(dAtA, i, uint64(len(m.Owner)))
		i += copy(dAtA[i:], m.Owner)
	}
	if len(m.Endpoint) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTopicData(dAtA, i, uint64(len(m.Endpoint)))
		i += copy(dAtA[i:], m.Endpoint)
	}
	if len(m.Protocol) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintTopicData(dAtA, i, uint64(len(m.Protocol)))
		i += copy(dAtA[i:], m.Protocol)
	}
	if m.RawDelivery {
		dAtA[i] = 0x28
		i++
		if m.RawDelivery {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Pending {
		dAtA[i] = 0x30
		i++
		if m.Pending {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *Topic) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Topic) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Arn) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTopicData(dAtA, i, uint64(len(m.Arn)))
		i += copy(dAtA[i:], m.Arn)
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTopicData(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.DisplayName) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTopicData(dAtA, i, uint64(len(m.DisplayName)))
		i += copy(dAtA[i:], m.DisplayName)
	}
	if len(m.Policy) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintTopicData(dAtA, i, uint64(len(m.Policy)))
		i += copy(dAtA[i:], m.Policy)
	}
	if len(m.DeliveryPolicy) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintTopicData(dAtA, i, uint64(len(m.DeliveryPolicy)))
		i += copy(dAtA[i:], m.DeliveryPolicy)
	}
	if len(m.EffectiveDeliveryPolicy) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintTopicData(dAtA, i, uint64(len(m.EffectiveDeliveryPolicy)))
		i += copy(dAtA[i:], m.EffectiveDeliveryPolicy)
	}
	if m.DeletedSubscriptions != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintTopicData(dAtA, i, uint64(m.DeletedSubscriptions))
	}
	if len(m.SqsSubscriptions) > 0 {
		for k, _ := range m.SqsSubscriptions {
			dAtA[i] = 0x42
			i++
			v := m.SqsSubscriptions[k]
			msgSize := 0
			if v != nil {
				msgSize = v.Size()
				msgSize += 1 + sovTopicData(uint64(msgSize))
			}
			mapSize := 1 + len(k) + sovTopicData(uint64(len(k))) + msgSize
			i = encodeVarintTopicData(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintTopicData(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			if v != nil {
				dAtA[i] = 0x12
				i++
				i = encodeVarintTopicData(dAtA, i, uint64(v.Size()))
				n1, err := v.MarshalTo(dAtA[i:])
				if err != nil {
					return 0, err
				}
				i += n1
			}
		}
	}
	if len(m.OtherSubscriptions) > 0 {
		for k, _ := range m.OtherSubscriptions {
			dAtA[i] = 0x4a
			i++
			v := m.OtherSubscriptions[k]
			msgSize := 0
			if v != nil {
				msgSize = v.Size()
				msgSize += 1 + sovTopicData(uint64(msgSize))
			}
			mapSize := 1 + len(k) + sovTopicData(uint64(len(k))) + msgSize
			i = encodeVarintTopicData(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintTopicData(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			if v != nil {
				dAtA[i] = 0x12
				i++
				i = encodeVarintTopicData(dAtA, i, uint64(v.Size()))
				n2, err := v.MarshalTo(dAtA[i:])
				if err != nil {
					return 0, err
				}
				i += n2
			}
		}
	}
	return i, nil
}

func (m *TopicNames) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TopicNames) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Topics) > 0 {
		for _, s := range m.Topics {
			dAtA[i] = 0xa
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func encodeVarintTopicData(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Subscription) Size() (n int) {
	var l int
	_ = l
	l = len(m.Arn)
	if l > 0 {
		n += 1 + l + sovTopicData(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTopicData(uint64(l))
	}
	l = len(m.Endpoint)
	if l > 0 {
		n += 1 + l + sovTopicData(uint64(l))
	}
	l = len(m.Protocol)
	if l > 0 {
		n += 1 + l + sovTopicData(uint64(l))
	}
	if m.RawDelivery {
		n += 2
	}
	if m.Pending {
		n += 2
	}
	return n
}

func (m *Topic) Size() (n int) {
	var l int
	_ = l
	l = len(m.Arn)
	if l > 0 {
		n += 1 + l + sovTopicData(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTopicData(uint64(l))
	}
	l = len(m.DisplayName)
	if l > 0 {
		n += 1 + l + sovTopicData(uint64(l))
	}
	l = len(m.Policy)
	if l > 0 {
		n += 1 + l + sovTopicData(uint64(l))
	}
	l = len(m.DeliveryPolicy)
	if l > 0 {
		n += 1 + l + sovTopicData(uint64(l))
	}
	l = len(m.EffectiveDeliveryPolicy)
	if l > 0 {
		n += 1 + l + sovTopicData(uint64(l))
	}
	if m.DeletedSubscriptions != 0 {
		n += 1 + sovTopicData(uint64(m.DeletedSubscriptions))
	}
	if len(m.SqsSubscriptions) > 0 {
		for k, v := range m.SqsSubscriptions {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovTopicData(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovTopicData(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovTopicData(uint64(mapEntrySize))
		}
	}
	if len(m.OtherSubscriptions) > 0 {
		for k, v := range m.OtherSubscriptions {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovTopicData(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovTopicData(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovTopicData(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *TopicNames) Size() (n int) {
	var l int
	_ = l
	if len(m.Topics) > 0 {
		for _, s := range m.Topics {
			l = len(s)
			n += 1 + l + sovTopicData(uint64(l))
		}
	}
	return n
}

func sovTopicData(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTopicData(x uint64) (n int) {
	return sovTopicData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Subscription) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Subscription{`,
		`Arn:` + fmt.Sprintf("%v", this.Arn) + `,`,
		`Owner:` + fmt.Sprintf("%v", this.Owner) + `,`,
		`Endpoint:` + fmt.Sprintf("%v", this.Endpoint) + `,`,
		`Protocol:` + fmt.Sprintf("%v", this.Protocol) + `,`,
		`RawDelivery:` + fmt.Sprintf("%v", this.RawDelivery) + `,`,
		`Pending:` + fmt.Sprintf("%v", this.Pending) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Topic) String() string {
	if this == nil {
		return "nil"
	}
	keysForSqsSubscriptions := make([]string, 0, len(this.SqsSubscriptions))
	for k, _ := range this.SqsSubscriptions {
		keysForSqsSubscriptions = append(keysForSqsSubscriptions, k)
	}
	sortkeys.Strings(keysForSqsSubscriptions)
	mapStringForSqsSubscriptions := "map[string]*Subscription{"
	for _, k := range keysForSqsSubscriptions {
		mapStringForSqsSubscriptions += fmt.Sprintf("%v: %v,", k, this.SqsSubscriptions[k])
	}
	mapStringForSqsSubscriptions += "}"
	keysForOtherSubscriptions := make([]string, 0, len(this.OtherSubscriptions))
	for k, _ := range this.OtherSubscriptions {
		keysForOtherSubscriptions = append(keysForOtherSubscriptions, k)
	}
	sortkeys.Strings(keysForOtherSubscriptions)
	mapStringForOtherSubscriptions := "map[string]*Subscription{"
	for _, k := range keysForOtherSubscriptions {
		mapStringForOtherSubscriptions += fmt.Sprintf("%v: %v,", k, this.OtherSubscriptions[k])
	}
	mapStringForOtherSubscriptions += "}"
	s := strings.Join([]string{`&Topic{`,
		`Arn:` + fmt.Sprintf("%v", this.Arn) + `,`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`DisplayName:` + fmt.Sprintf("%v", this.DisplayName) + `,`,
		`Policy:` + fmt.Sprintf("%v", this.Policy) + `,`,
		`DeliveryPolicy:` + fmt.Sprintf("%v", this.DeliveryPolicy) + `,`,
		`EffectiveDeliveryPolicy:` + fmt.Sprintf("%v", this.EffectiveDeliveryPolicy) + `,`,
		`DeletedSubscriptions:` + fmt.Sprintf("%v", this.DeletedSubscriptions) + `,`,
		`SqsSubscriptions:` + mapStringForSqsSubscriptions + `,`,
		`OtherSubscriptions:` + mapStringForOtherSubscriptions + `,`,
		`}`,
	}, "")
	return s
}
func (this *TopicNames) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TopicNames{`,
		`Topics:` + fmt.Sprintf("%v", this.Topics) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTopicData(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Subscription) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTopicData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Subscription: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Subscription: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Arn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopicData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Arn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopicData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Endpoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopicData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Endpoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Protocol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopicData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Protocol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawDelivery", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RawDelivery = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pending", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Pending = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTopicData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTopicData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Topic) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTopicData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Topic: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Topic: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Arn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopicData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Arn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopicData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisplayName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopicData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisplayName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Policy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopicData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Policy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeliveryPolicy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopicData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeliveryPolicy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectiveDeliveryPolicy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopicData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EffectiveDeliveryPolicy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedSubscriptions", wireType)
			}
			m.DeletedSubscriptions = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeletedSubscriptions |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SqsSubscriptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTopicData
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SqsSubscriptions == nil {
				m.SqsSubscriptions = make(map[string]*Subscription)
			}
			var mapkey string
			var mapvalue *Subscription
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTopicData
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTopicData
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthTopicData
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTopicData
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= (int(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthTopicData
					}
					postmsgIndex := iNdEx + mapmsglen
					if mapmsglen < 0 {
						return ErrInvalidLengthTopicData
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &Subscription{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipTopicData(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthTopicData
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.SqsSubscriptions[mapkey] = mapvalue
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OtherSubscriptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTopicData
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OtherSubscriptions == nil {
				m.OtherSubscriptions = make(map[string]*Subscription)
			}
			var mapkey string
			var mapvalue *Subscription
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTopicData
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTopicData
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthTopicData
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTopicData
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= (int(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthTopicData
					}
					postmsgIndex := iNdEx + mapmsglen
					if mapmsglen < 0 {
						return ErrInvalidLengthTopicData
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &Subscription{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipTopicData(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthTopicData
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.OtherSubscriptions[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTopicData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTopicData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TopicNames) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTopicData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TopicNames: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TopicNames: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Topics", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopicData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Topics = append(m.Topics, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTopicData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTopicData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTopicData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTopicData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTopicData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthTopicData
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTopicData
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTopicData(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTopicData = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTopicData   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("server/snsproto/dbdata/topic_data.proto", fileDescriptorTopicData) }

var fileDescriptorTopicData = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xae, 0x97, 0x26, 0xeb, 0x5e, 0x27, 0x18, 0xa6, 0x63, 0xa1, 0x07, 0x2b, 0x14, 0xd0, 0x2a,
	0x84, 0x5a, 0x69, 0xbb, 0xa0, 0x1d, 0xd1, 0xb8, 0xc2, 0x94, 0x21, 0x24, 0xc4, 0x21, 0x4a, 0x13,
	0x0f, 0xa2, 0x05, 0x3b, 0xb3, 0xbd, 0x56, 0xb9, 0xf1, 0x13, 0xf8, 0x19, 0x48, 0xfc, 0x11, 0x8e,
	0x3b, 0x72, 0xa4, 0x81, 0x03, 0xc7, 0xfd, 0x04, 0x64, 0x3b, 0x99, 0xda, 0x52, 0x4e, 0xdc, 0xfc,
	0xde, 0xf7, 0x7d, 0xcf, 0x5f, 0xf2, 0x3d, 0xc3, 0xbe, 0xa4, 0x62, 0x4a, 0xc5, 0x58, 0x32, 0x59,
	0x08, 0xae, 0xf8, 0x38, 0x9d, 0xa4, 0xb1, 0x8a, 0xc7, 0x8a, 0x17, 0x59, 0x12, 0xe9, 0xe3, 0xc8,
	0xf4, 0xb1, 0x67, 0x81, 0xc1, 0x57, 0x04, 0xdb, 0xa7, 0x97, 0x13, 0x99, 0x88, 0xac, 0x50, 0x19,
	0x67, 0x78, 0x07, 0x9c, 0x58, 0x30, 0x1f, 0x05, 0x68, 0xb8, 0x15, 0xea, 0x23, 0xee, 0x81, 0xcb,
	0x67, 0x8c, 0x0a, 0x7f, 0xc3, 0xf4, 0x6c, 0x81, 0xfb, 0xd0, 0xa1, 0x2c, 0x2d, 0x78, 0xc6, 0x94,
	0xef, 0x18, 0xe0, 0xa6, 0xd6, 0x98, 0xb9, 0x25, 0xe1, 0xb9, 0xdf, 0xb6, 0x58, 0x53, 0xe3, 0x07,
	0xb0, 0x2d, 0xe2, 0x59, 0x94, 0xd2, 0x3c, 0x9b, 0x52, 0x51, 0xfa, 0x6e, 0x80, 0x86, 0x9d, 0xb0,
	0x2b, 0xe2, 0xd9, 0x71, 0xdd, 0xc2, 0x3e, 0x6c, 0x16, 0x94, 0xa5, 0x19, 0x7b, 0xef, 0x7b, 0x06,
	0x6d, 0xca, 0xc1, 0xaf, 0x36, 0xb8, 0xaf, 0xf5, 0xa7, 0xac, 0xb1, 0x89, 0xa1, 0xcd, 0xe2, 0x8f,
	0xb4, 0x76, 0x69, 0xce, 0xfa, 0xb2, 0x34, 0x93, 0x45, 0x1e, 0x97, 0x91, 0xc1, 0xac, 0xd1, 0x6e,
	0xdd, 0x7b, 0xa9, 0x29, 0xf7, 0xc0, 0x2b, 0x78, 0x9e, 0x25, 0x65, 0xed, 0xb4, 0xae, 0xf0, 0x3e,
	0xdc, 0x6e, 0x3c, 0x46, 0x35, 0xc1, 0x35, 0x84, 0x5b, 0x4d, 0xfb, 0xc4, 0x12, 0x8f, 0xe0, 0x3e,
	0x3d, 0x3b, 0xa3, 0x89, 0xca, 0xa6, 0x34, 0x5a, 0x95, 0x78, 0x46, 0xb2, 0x77, 0x43, 0x38, 0x5e,
	0xd6, 0x1e, 0xc2, 0x6e, 0x4a, 0x73, 0xaa, 0x68, 0x1a, 0xc9, 0x85, 0x10, 0xa4, 0xbf, 0x19, 0xa0,
	0xa1, 0x13, 0xf6, 0x6a, 0x70, 0x31, 0x20, 0x89, 0x4f, 0xe0, 0x8e, 0xbc, 0x90, 0x2b, 0x82, 0x4e,
	0xe0, 0x0c, 0xbb, 0x07, 0x0f, 0x47, 0x36, 0xd6, 0x91, 0xf9, 0x49, 0xa3, 0xd3, 0x0b, 0xb9, 0x24,
	0x7d, 0xc1, 0x94, 0x28, 0xc3, 0x1d, 0xb9, 0xd2, 0xc6, 0x6f, 0xe0, 0x2e, 0x57, 0x1f, 0xa8, 0x58,
	0x99, 0xb9, 0x65, 0x66, 0x3e, 0x5e, 0x9e, 0xf9, 0x4a, 0x13, 0xd7, 0x4c, 0xc5, 0xfc, 0x2f, 0xa0,
	0xff, 0x16, 0x76, 0xd7, 0x5a, 0xd0, 0xe9, 0x9d, 0xd3, 0xb2, 0x49, 0xef, 0x9c, 0x96, 0xf8, 0x09,
	0xb8, 0xd3, 0x38, 0xbf, 0xb4, 0xf1, 0x75, 0x0f, 0x7a, 0xcd, 0xa5, 0x8b, 0xe2, 0xd0, 0x52, 0x8e,
	0x36, 0x9e, 0xa1, 0xfe, 0x3b, 0xd8, 0xfb, 0x87, 0x93, 0xff, 0x1f, 0x3e, 0x78, 0x04, 0x60, 0x3e,
	0x56, 0x2f, 0x88, 0xd4, 0x1b, 0x62, 0x9e, 0x8f, 0xf4, 0x51, 0xe0, 0xe8, 0x0d, 0xb1, 0xd5, 0xf3,
	0xa7, 0x57, 0x73, 0xd2, 0xfa, 0x3e, 0x27, 0xad, 0xeb, 0x39, 0x41, 0x9f, 0x2a, 0x82, 0xbe, 0x54,
	0x04, 0x7d, 0xab, 0x08, 0xba, 0xaa, 0x08, 0xfa, 0x51, 0x11, 0xf4, 0xbb, 0x22, 0xad, 0xeb, 0x8a,
	0xa0, 0xcf, 0x3f, 0x49, 0x6b, 0xe2, 0x99, 0x17, 0x70, 0xf8, 0x27, 0x00, 0x00, 0xff, 0xff, 0x8a,
	0x1f, 0x1f, 0x6a, 0xa2, 0x03, 0x00, 0x00,
}
