package pqueue

const PRM_ID = "ID"
const PRM_POP_WAIT_TIMEOUT = "WAITTIMEOUT"
const PRM_LOCK_TIMEOUT = "LOCKTIMEOUT"
const PRM_PRIORITY = "PRIORITY"
const PRM_LIMIT = "LIMIT"
const PRM_PAYLOAD = "PAYLOAD"
const PRM_DELIVERY_INTERVAL = "DELIVERYINTERVAL"
